title: Laurenz Sommerlad
description: I’m Laurenz, 21 y/o and passionate about AI, Robotics & Entrepreneurship. I lead the Venture Department at TUM.ai, conduct research at the LMU Hospital to predict rare child diseases, and build an Autonomous Mars Rover with WARR Space Robotics.
